### ISSUE TITLE
Use/modify this to act like image map? 

### ISSUE THREAD

**Issue by gar37bic** [picturae/openseadragonselection#10]
This selection tool is great - I just learned about openseadragon itself only in the last couple of days.  What I now need is as follows: I have an image with many 'boxes' on it - akin to a flow chart.  Ideally when the mouse cursor is over a box, the box outline would highlight. Then if the user clicks the mouse, an action is performed: a new tab is opened and loads the page at the address associated with the box, so the user can learn more about the topic in the box.

I'm old, but pretty new WRT javascript and Ajax but I have hacked around a bit.  Would this be best to do this as a separate plugin? Or is there a way to set the parameters of this plugin to accomplish something similar?

In any case, thanks for producing this and making it available!

**Comment by MindFreeze** [comment]
I think what you need is overlays. This is an OSD internal feature/option. I think you can pass in html elements like divs and coordinates to the viewer on start up. Then you can bind onClick and other events to those elements. Look around the viewer's docs for overlays.
If you need to dynamically select the overlays/boxes, you can use this plugin and call viewer.addOverlay() when a selection s made.

I can't provide specific links to docs right now because I am writing from a phone. But feel free to ask question if I am not making much sense.
